version: '3'
services:

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - /data/html:/var/www/html:ro

  nginx-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-gen
    restart: always
    # user: "1001:993"
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    environment:
      - DEFAULT_HOST=zeropage.org

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx

  xpressengine:
    build: ./xpressengine
    container_name: xpressengine
    restart: always
    depends_on:
      - db
    volumes:
      - /data/html/xpressengine:/var/www/html:ro
      - /data/html/xpressengine/files:/var/www/html/files:rw
    environment:
      - VIRTUAL_HOST=zeropage.org,www.zeropage.org
      - LETSENCRYPT_HOST=zeropage.org,www.zeropage.org
      - LETSENCRYPT_EMAIL=zeropage@zeropage.org

  moniwiki:
    build: ./moniwiki
    container_name: moniwiki
    restart: always
    volumes:
      - /data/html/moniwiki:/var/www/html:ro
      - /data/html/moniwiki/data:/var/www/html/data:rw
      - /data/html/moniwiki/pds:/var/www/html/pds:rw
      - /data/html/moniwiki/_cache:/var/www/html/_cache:rw
    environment:
      - VIRTUAL_HOST=wiki.zeropage.org
      - LETSENCRYPT_HOST=wiki.zeropage.org
      - LETSENCRYPT_EMAIL=zeropage@zeropage.org

  mattermost:
    image: mattermost/mattermost-team-edition:7.1
    container_name: mattermost
    restart: always
    depends_on:
      - mysql-mattermost
    ports:
      - "8443:8443/udp"
    volumes:
      - /data/html/mattermost/config:/mattermost/config:rw
      - /data/html/mattermost/data:/mattermost/data:rw
      - /data/html/mattermost/logs:/mattermost/logs:rw
      - /data/html/mattermost/plugins:/mattermost/plugins:rw
      - /data/html/mattermost/client/plugins:/mattermost/client/plugins:rw
      - /data/html/mattermost/bleve-indexes:/mattermost/bleve-indexes:rw
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_SQLSETTINGS_DATASOURCE
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
      - VIRTUAL_HOST=chat.zeropage.org,chat.zp.ai
      - VIRTUAL_PORT=8065
      - LETSENCRYPT_HOST=chat.zeropage.org,chat.zp.ai
      - LETSENCRYPT_EMAIL=zeropage@zeropage.org

  db:
    image: mariadb:10.3
    container_name: mariadb
    restart: always
    user: "27:27"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    volumes:
      - /var/lib/mysql:/var/lib/mysql:rw
      # - /var/run/mysqld:/var/run/mysqld:rw
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  mysql-mattermost:
    image: mysql:8.0
    container_name: mysql-mattermost
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-mattermost/etc/mysql/conf.d/mattermost-search.cnf:/etc/mysql/conf.d/mattermost-search.cnf:ro
      - /var/lib/mysql_mattermost:/var/lib/mysql:rw
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mattermost
      - MYSQL_USER=mattermost
      - MYSQL_PASSWORD=${MM_MYSQL_PASSWORD}

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=pma.zeropage.org
      - LETSENCRYPT_HOST=pma.zeropage.org
      - LETSENCRYPT_EMAIL=zeropage@zeropage.org

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     - VIRTUAL_HOST=adminer.zeropage.org
  #     - LETSENCRYPT_HOST=adminer.zeropage.org
  #     - LETSENCRYPT_EMAIL=zeropage@zeropage.org

