services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8088:8080" # Traefik 대시보드 포트
    command:
      - "--api.insecure=true" # 웹 대시보드 활성화 (생산 환경에서는 보안을 설정해야 함)
      - "--api.dashboard=true" # 대시보드 활성화
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=zeropage@zeropage.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      # Traefik 대시보드를 위한 설정
      - "traefik.http.routers.traefik.rule=Host(`traefik.zeropage.org`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"

  caddy:
    image: caddy:alpine
    container_name: caddy-static
    restart: always
    volumes:
      - /data/html/caddy:/usr/share/caddy:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-files.rule=Host(`static.zeropage.org`)"
      - "traefik.http.routers.static-files.entrypoints=websecure"
      - "traefik.http.routers.static-files.tls.certresolver=myresolver"
      - "traefik.http.services.static-files.loadbalancer.server.port=80"
  xpressengine:
    build: ./xpressengine
    container_name: xpressengine
    restart: always
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xpressengine.rule=Host(`zeropage.org`) || Host(`www.zeropage.org`)"
      - "traefik.http.routers.xpressengine.entrypoints=websecure"
      - "traefik.http.routers.xpressengine.tls.certresolver=myresolver"
    volumes:
      - /data/html/xpressengine:/var/www/html:ro
      - /data/html/xpressengine/files:/var/www/html/files:rw

  moniwiki:
    image: zeropageorg_moniwiki:latest
    container_name: moniwiki
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moniwiki.rule=Host(`wiki.zeropage.org`)"
      - "traefik.http.routers.moniwiki.entrypoints=websecure"
      - "traefik.http.routers.moniwiki.tls.certresolver=myresolver"
    volumes:
      - /data/html/moniwiki:/var/www/html:ro
      - /data/html/moniwiki/data:/var/www/html/data:rw
      - /data/html/moniwiki/pds:/var/www/html/pds:rw
      - /data/html/moniwiki/_cache:/var/www/html/_cache:rw

  mattermost:
    image: mattermost/mattermost-team-edition:9.11.5
    container_name: mattermost
    restart: always
    depends_on:
      - mysql-mattermost
    ports:
      - "8443:8443/udp"
      - "8065:8065/udp"
    security_opt:
      - seccomp:unconfined
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.rule=Host(`chat.zeropage.org`) || Host(`chat.zp.ai`)"
      - "traefik.http.routers.mattermost.entrypoints=websecure"
      - "traefik.http.routers.mattermost.tls.certresolver=myresolver"
    volumes:
      - /data/html/mattermost/config:/mattermost/config:rw
      - /data/html/mattermost/data:/mattermost/data:rw
      - /data/html/mattermost/logs:/mattermost/logs:rw
      - /data/html/mattermost/plugins:/mattermost/plugins:rw
      - /data/html/mattermost/client/plugins:/mattermost/client/plugins:rw
      - /data/html/mattermost/bleve-indexes:/mattermost/bleve-indexes:rw
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_SQLSETTINGS_DATASOURCE
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes

  db:
    image: mariadb:10.3
    container_name: mariadb
    restart: always
    user: "27:27"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    #    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake --skip-grant-tables --skip-networking
    volumes:
      - /var/lib/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_PASSWORD=${MM_MYSQL_PASSWORD}

  mysql-mattermost:
    image: mysql:8.0
    container_name: mysql-mattermost
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-mattermost/etc/mysql/conf.d/mattermost-search.cnf:/etc/mysql/conf.d/mattermost-search.cnf:ro
      - /var/lib/mysql_mattermost:/var/lib/mysql:rw
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mattermost
      - MYSQL_USER=mattermost
      - MYSQL_PASSWORD=${MM_MYSQL_PASSWORD}

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myadmin.rule=Host(`pma.zeropage.org`)"
      - "traefik.http.routers.myadmin.entrypoints=websecure"
      - "traefik.http.routers.myadmin.tls.certresolver=myresolver"

  portal:
    image: ghcr.io/zeropage/zp-portal-page:latest
    ports:
      - "3000:3000"
    restart: always
    container_name: portal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal.rule=Host(`portal.zeropage.org`)"
      - "traefik.http.routers.portal.entrypoints=websecure"
      - "traefik.http.routers.portal.tls.certresolver=myresolver"

  mysql2024:
    image: mysql:8.0
    container_name: mysql2024
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql2024/etc/mysql/conf.d/mysql2024-search.cnf:/etc/mysql/conf.d/mysql2024-search.cnf:ro
      - /var/lib/mysql2024:/var/lib/mysql:rw
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=${MYSQL2024_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL2024_ROOT_PASSWORD}
  #    초기에 1개의 사용자만 자동으로 생성할 수 있습니다. keycloak을 위한 계정은 직접 생성하여야합니다.
  mediawiki:
    image: mediawiki:1.39.8
    container_name: mediawiki
    restart: always
    depends_on:
      - mysql2024
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediawiki.rule=Host(`mediawiki.zeropage.org`)"
      - "traefik.http.routers.mediawiki.entrypoints=websecure"
      - "traefik.http.routers.mediawiki.tls.certresolver=myresolver"
      - "traefik.http.middlewares.mediawiki-headers.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      - "traefik.http.routers.mediawiki.middlewares=mediawiki-headers"
    volumes:
      - /data/html/mediawiki:/var/www/html:rw
      - /data/html/mediawiki_use_local_bin:/usr/local/bin:rw
    environment:
      - MEDIAWIKI_DB_HOST=mysql2024
      - MEDIAWIKI_DB_USER=mediawiki
      - MEDIAWIKI_DB_PASSWORD=${MYSQL2024_PASSWORD}
      - MEDIAWIKI_DB_NAME=mediawiki

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command:
      #      - "-v"
      - "start"
    #      - "build"
    #      - "--verbose"
    #      - "--optimized"
    #      - "start"
    #      - "--hostname=https://sso.zeropage.org"
    #      - "--hostname-admin=https://sso2.zeropage.org"
    #      - "--hostname-strict=false"
    environment:
      KC_HOSTNAME: https://sso.zeropage.org
      #      KC_HOSTNAME_ADMIN: https://sso2.zeropage.org
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql2024/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      PROXY_ADDRESS_FORWARDING: true
    #     KC_PROXY: edge
    ports:
      - 8080:8080
      - 8443:8443
    restart: always
    depends_on:
      - mysql2024
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`sso.zeropage.org`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.service=keycloak"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.keycloak-stripprefix.stripprefix.prefixes=/auth"
      - "traefik.http.routers.keycloak.middlewares=keycloak-stripprefix"
      - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
    volumes:
      - /data/html/keycloak:/opt/keycloak
  cz_portal_be:
    image: ghcr.io/zeropage/cz_portal_be
    container_name: cz_portal_be
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nest-project.rule=Host(`api.zeropage.org`)"
      - "traefik.http.routers.nest-project.entrypoints=websecure"
      - "traefik.http.routers.nest-project.tls.certresolver=myresolver"
      - "traefik.http.services.nest-project.loadbalancer.server.port=5000"
  cz_portal_fe:
    image: ghcr.io/zeropage/cz_portal_fe:latest
    container_name: cz_portal_fe
    restart: always
    ports:
      - "3000:4173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.zeropage.org
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vue-project.rule=Host(`clug.zeropage.org`)"
      - "traefik.http.routers.vue-project.entrypoints=websecure"
      - "traefik.http.routers.vue-project.tls.certresolver=myresolver"
      - "traefik.http.services.vue-project.loadbalancer.server.port=4173"
  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
